project:
  type: book
  output-dir: docs

book:
  title: "A Yooper Ski Jumping Legacy"
  author: "Craig Savonen"
  date: "December 6, 2025"
  favicon: img/favicon.png
  bread-crumbs: false

  page-navigation: true
  search: true
  repo-url: https://github.com/fhdsl/yooper-ski-jump
  repo-actions: [edit] 
  
  chapters:
    - index.qmd
  
  sidebar: 
    logo: "img/logo.png"
    logo-alt: "Yooper Ski Jumping - Flights of Legacy"
    foreground: "#1B365D"
  
  page-footer:
    left: |
      Written by Craig Savonen. Technical editing and formatting by Candace Savonen.
    center: |
      This work is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/" style="color: #fff;">CC BY-NC 4.0</a>.
      <br>
      Built with <a href="https://quarto.org/" style="color: #fff;">Quarto</a> using 
      <a href="https://github.com/ottrproject/OTTR_Quarto" style="color: #fff;">OTTR</a>.
    right: 
      - icon: github
        href: https://github.com/fhdsl/yooper-ski-jump

bibliography: references.bib

format:
  html:
    grid:
       sidebar-width: 260px
    css: style.css
    linkcolor: "#00C1D5"
    mainfont: "Karla"
    
    sidebar: true
    toc: true
  
    code-link: true
    code-copy: true
    
    link-external-newwindow: true
  
    image: resources/logo/yooper_ski_jump_logo.png
    license: "CC BY-NC"
knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"
