project:
  type: website
  output-dir: docs

website:
  title: "A Yooper Ski Jumping Legacy"
  favicon: img/favicon.png
  
  search: true
  repo-url: https://github.com/fhdsl/yooper-ski-jump
  repo-actions: [edit]
  
  sidebar:
    style: docked
    logo: "img/logo.png"
    logo-alt: "Yooper Ski Jumping - Flights of Legacy"
    foreground: "#1B365D"
  
  page-footer:
    left: |
      Written by Craig Savonen. Technical editing and formatting by Candace Savonen.
    center: |
      This work is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/" style="color: #fff;">CC BY-NC 4.0</a>.
      <br>
      Built with <a href="https://quarto.org/" style="color: #fff;">Quarto</a> using 
      <a href="https://github.com/ottrproject/OTTR_Quarto" style="color: #fff;">OTTR</a>.
    right: 
      - icon: github
        href: https://github.com/fhdsl/yooper-ski-jump

bibliography: references.bib

format:
  html:
    grid:
       sidebar-width: 300px
    css: style.css
    linkcolor: "#00C1D5"
    mainfont: "Karla"
    
    toc: true
    toc-depth: 2
    toc-title: "Contents"
  
    code-link: true
    code-copy: true
    
    link-external-newwindow: true
  
    image: resources/logo/yooper_ski_jump_logo.png
    license: "CC BY-NC"

knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"
